FROM node:20-trixie
ARG TARGETARCH

# Install linux dependencies
ARG DEPENDENCIES="                    \
        ca-certificates              \
        openjdk-21-jdk-headless       \
        curl                          \
        wget"

ARG APT_MIRROR=http://deb.debian.org

RUN set -ex \
    && sed -i "s@http://.*.debian.org@${APT_MIRROR}@g" /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && apt-get -y install --no-install-recommends ${DEPENDENCIES} \
    && echo "no" | dpkg-reconfigure dash \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

# Install tools and dependencies
RUN set -ex \
    && wget https://github.com/jumpserver-dev/healthcheck/releases/latest/download/check_linux_${TARGETARCH}.deb \
    && dpkg -i check_linux_${TARGETARCH}.deb \
    && rm -f check_linux_${TARGETARCH}.deb

ARG WISP_VERSION=v0.2.13
RUN set -ex \
    && wget https://github.com/jumpserver/wisp/releases/download/${WISP_VERSION}/wisp_linux_${TARGETARCH}.deb \
    && dpkg -i wisp_linux_${TARGETARCH}.deb \
    && rm -f wisp_linux_${TARGETARCH}.deb

# Install NPM dependencies
WORKDIR /opt/chen/frontend
COPY frontend/package.json frontend/package-lock.json frontend/yarn.lock ./

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn,sharing=locked,id=chen \
    npm install

# Install Maven dependencies
ARG MAVEN_VERSION=3.9.15
ARG USER_HOME_DIR="/root"
ARG BASE_URL=https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries
ARG MAVEN_MIRROR=https://repo.maven.apache.org/maven2
ENV MAVEN_HOME=/usr/share/maven
ENV MAVEN_CONFIG="$USER_HOME_DIR/.m2"

WORKDIR /opt/chen

COPY settings.xml pom.xml ./
COPY backend/pom.xml backend/
COPY backend/framework/pom.xml  backend/framework/
COPY backend/web/pom.xml  backend/web/
COPY backend/wisp/pom.xml  backend/wisp/
COPY backend/modules/pom.xml  backend/modules/

RUN set -ex \
    && mkdir -p /usr/share/maven /usr/share/maven/ref \
    && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
    && rm -f /tmp/apache-maven.tar.gz \
    && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn \
    && mkdir -p /root/.m2 \
    && mkdir -p /opt/chen/frontend/dist \
    && sed -i "s@https://repo.maven.apache.org/maven2@${MAVEN_MIRROR}@g" settings.xml \
    && cp -f settings.xml /root/.m2/ \
    && mvn clean install