ARG VERSION=dev

FROM jumpserver/chen:${VERSION}-ce
ARG TARGETARCH

ARG DEPENDENCIES="                    \
        iputils-ping                  \
        telnet"                   

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=chen \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=chen \
    set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${DEPENDENCIES}
    